### PR TITLE
Respect hidden attribute when converting to CSV, fixes #755

### LINKED ISSUE #755: sheet_to_csv utility method doesn't respect hidden columns
If sheet object contains hidden columns, I should not find them in the output of `csv`.

### PR DESCRIPTION
**Pull request by the-spyke**
Fixes #755

### CODE REVIEW

**Comment by SheetJSDev** [comment]
Looks good! can you squash down to one commit and keep the one-line summary to 50 chars?  Something like:

```
`skipHidden` option for sheet_to_csv (fixes #755)                       
                                                                        
Note: Excel CSV conversion includes hidden rows and columns by default  
```

**Comment by the-spyke** [comment]
@SheetJSDev Sure.

What is `tests/core.js` file for? I've copied tests to this file too, but I don't know how to run it.

**Comment by SheetJSDev** [comment]
@the-spyke that file holds the browser tests.  Those are usually run before each release.

(this is mentioned in https://github.com/sheetjs/js-xlsx#browser -- if something is missing or unclear, please suggest fixes :)

If you want to run the tests:

- Run a web server in the `tests` directory.  The included `Makefile` has a target `ctestserv`:

```Makefile
.PHONY: ctestserv
ctestserv: ## Start a test server on port 8000
	@cd tests && python -mSimpleHTTPServer
```

- Go to the page.  `python -mSimpleHTTPServer` serves on port 8000 by default, so you can access http://localhost:8000/ from your web browser.

That page also powers the sauce labs cross-browser tests.  You probably noticed a big badge in the README:



The details, including screen recordings, of the last few runs are available at http://saucelabs.com/u/sheetjs

**Comment by SheetJSDev** [comment]
@the-spyke  did you intend to close this?

**Comment by the-spyke** [comment]
@SheetJSDev I've completely messed up with squashing and branches. Now trying to make another branch. I'm sorry.

**Comment by SheetJSDev** [comment]
@the-spyke no rush and no need to apologize :)

**Pull request closed without merging**
