### PR TITLE
Update xlsx.js  

### PR DESCRIPTION
**Pull request by LieJiang**
write file whit bookSST true, it goes wrong,this can fix it.

### CODE REVIEW

**Comment by SheetJSDev** [comment]
@LieJiang If the value is undefined it is most likely a stub cell.  The cell shouldn't be written in the first place.

Check your email

**Comment by LieJiang** [comment]
If the conversion type is not enforced, it does not work with 'do not have the match function'

**Comment by SheetJSDev** [comment]
@LieJiang I understand :) What I am saying is that the error is coming because of a bad cell.  For example:

```js
XLSX.write({SheetNames:["Sheet1"], Sheets:{Sheet1:{"!ref":"A1:A1", A1:{t:"s", v:3}}}},{bookType:'xlsx', bookSST:true, type:'buffer'});
XLSX.write({SheetNames:["Sheet1"], Sheets:{Sheet1:{"!ref":"A1:A1", A1:{t:"s", v:null}}}},{bookType:'xlsx', bookSST:true, type:'buffer'});
```

In the first case, the cell is a string cell with a numeric value. In this case, String will do the right thing, writing the text "3" to the cell.

In the second case, the cell is a string
cell with a null value.  If you use the `String` conversion, the output file will have the text `null` in those cells.  That is incorrect.  If the text is null it should not write the data in the first place.

This will require a few more changes to other parts of the code.  Keep the PR open

**Comment by LieJiang** [comment]
We can add a filter before writing a file.

**Pull request closed without merging**
