### PR TITLE
Add Typescript definition for XLSX.utils.book_append_sheet

### PR DESCRIPTION
**Pull request by cthielen**
Adds the TypeScript definition for XLSX.utils.book_append_sheet().

### CODE REVIEW

**Comment by SheetJSDev** [comment]
The third argument `name` is optional and defaults to enumerating Sheet# until it finds an unused sheet name.

I looked into it a few days ago in response to [a related comment](https://github.com/SheetJS/js-xlsx/issues/365#issuecomment-308556738) and this is what I came up with:

```typescript
    /** Create a new workbook */
    book_new(): WorkBook;

    /** Append a worksheet to a workbook */
    book_append_sheet(workbook: WorkBook, worksheet: WorkSheet, name?: string): void;

    /** Set sheet visibility (visible/hidden/very hidden) */
    book_set_sheet_visibility(workbook: WorkBook, sheet: number|string, visibility: number): void;

    /** Set number format for a cell */
    cell_set_number_format(cell: CellObject, fmt: string|number): CellObject;

    /** Set hyperlink for a cell */
    cell_set_hyperlink(cell: CellObject, target: string, tooltip?: string): CellObject;

    /** Add comment to a cell */
    cell_add_comment(cell: CellObject, text: string, author?: string): void;

    /** Assign an Array Formula to a range */
    sheet_set_array_formula(ws: WorkSheet, range: Range|string, formula: string): WorkSheet;
```

If you could amend the commit to fix the third argument and possibly add the other function definitions, we can merge :)

**Comment by cthielen** [comment]
Thanks @SheetJSDev , I've updated the PR. 👍

**Comment by SheetJSDev** [comment]
Looks good, can you squash the two commits down to one and reduce the message length to 50 characters?  `Add missing TS definitions` suffices

**Comment by SheetJSDev** [comment]
We squashed the pull, thanks a lot @cthielen

**Comment by cthielen** [comment]
Thank you!

**Pull request merged**
