### PR TITLE
Fix file getter: letter case do not match

### PR DESCRIPTION
**Pull request by chikh**
Fixes the issue: https://github.com/SheetJS/js-xlsx/issues/439

### CODE REVIEW

**Comment by chaliy** [comment]
Have the same issue, is there any plans to apply this pull request?

**Comment by chikh** [comment]
@chaliy We've forked the repo (within private organization) and switched to this branch in our `package.json`. Since module is not maintained any more, it is better to find a substitution, but I can't find obvious one.

**Comment by chaliy** [comment]
@chikh aha doing the same right now. Already applied your pull request and now updating package.json. Thank you.

**Comment by chikh** [comment]
@chaliy You are welcome!

**Comment by willgriffin** [comment]
You may have better reception submitting the pull request to 

https://github.com/protobi/js-xlsx

Which is the branch I've forked and has quite a bit of further development on it

**Comment by chikh** [comment]
@willgriffin I've created PR https://github.com/protobi/js-xlsx/pull/46. I've noticed a very nice progress on the features and fixes so far!

**Pull request closed without merging**
